# Docker Compose override for CI/Testing
# This file is automatically used by docker-compose when present
version: '3.8'

services:
  # Override FastAPI for testing (now with embedded ChromaDB)
  fastapi:
    environment:
      - ENVIRONMENT=test
      - LOG_LEVEL=debug
      - CHROMA_PERSIST_DIRECTORY=/app/data/chroma
    # Use a smaller timeout for faster CI
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  # Override Redis for CI
  redis:
    command: redis-server --save "" --appendonly no
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  # Override frontend for CI (don't need full frontend in CI tests)
  frontend:
    environment:
      - FASTAPI_BASE_URL=http://fastapi:8000
      - NODE_ENV=test
