services:
  # Redis for session storage
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app-network
    profiles:
      - dev
      - prod
      - all

  # FastAPI Backend (with embedded ChromaDB)
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    ports:
      - "8000:8000"  # FastAPI backend
    depends_on:
      redis:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CHROMA_PERSIST_DIRECTORY=/app/data/chroma  # Embedded ChromaDB data directory
    volumes:
      - ./data:/app/data
      - ./documents:/app/documents
      - chromadb_data:/app/data/chroma  # Persistent storage for embedded ChromaDB
    networks:
      - app-network
    profiles:
      - dev
      - prod
      - all

  # Reflex UI Frontend
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.reflex
    ports:
      - "3000:3000"  # Reflex frontend
    depends_on:
      - fastapi
    environment:
      - FASTAPI_BASE_URL=http://fastapi:8000  # Internal Docker network URL
    networks:
      - app-network
    profiles:
      - dev
      - all

volumes:
  chromadb_data:
  redis_data:

networks:
  app-network:
    driver: bridge