version: '3.8'

services:
  redis:
    image: redis
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Frontend
      - "8000:8000"  # FastAPI Backend
    depends_on:
      - redis
      - chromadb
    networks:
      - app-network
      
  chromadb:
    image: chromadb/chroma:latest
    ports:
      - "8001:8001"  
    volumes:
      - chromadb_data:/chroma/chroma
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8001
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.reflex
    ports:
      - "3000:3000"
    depends_on:
      - fastapi
      - redis
      - chromadb
    environment:
      - FASTAPI_URL=http://fastapi:80  # Internal Docker network URL
      - API_BASE_URL=http://localhost:8000  # External URL for client-side requests
    networks:
      - app-network

  fastapi:
    build:
      context: ./src
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      chromadb:
        condition: service_healthy
    environment:
      - CHROMA_HOST=chromadb
      - CHROMA_PORT=8001
    networks:
      - app-network

volumes:
  chromadb_data:

networks:
  app-network:
    driver: bridge