FROM python:3.12-slim-bookworm

ARG uv=/root/.local/bin/uv

RUN apt-get update && apt-get install -y curl unzip  && rm -rf /var/lib/apt/lists/*

# Install uv
ADD --chmod=755 https://astral.sh/uv/install.sh /install.sh
RUN /install.sh && rm /install.sh

WORKDIR /app

# Copy source code
COPY . .

# Create virtualenv and install dependencies
ENV VIRTUAL_ENV=/app/.venv
ENV PATH="$VIRTUAL_ENV/bin:$PATH"
RUN $uv venv
RUN $uv sync --locked

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]