# Docker Compose override for CI/Testing
# This file is automatically used by docker-compose when present
version: '3.8'

services:
  # Override FastAPI for testing
  fastapi:
    environment:
      - ENVIRONMENT=test
      - LOG_LEVEL=debug
    # Use a smaller timeout for faster CI
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  # Override ChromaDB for faster startup in CI
  chromadb:
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8000
      - ANONYMIZED_TELEMETRY=False
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/heartbeat"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  # Override Redis for CI
  redis:
    command: redis-server --save "" --appendonly no
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  # Override frontend for CI (don't need full frontend in CI tests)
  frontend:
    environment:
      - FASTAPI_BASE_URL=http://fastapi:8000
      - NODE_ENV=test
