FROM python:3.12-slim-bookworm

ARG uv=/root/.local/bin/uv

RUN apt-get update && apt-get install -y curl unzip  && rm -rf /var/lib/apt/lists/*

# Install uv
ADD --chmod=755 https://astral.sh/uv/install.sh /install.sh
RUN /install.sh && rm /install.sh

WORKDIR /app

COPY . .

# Create virtualenv in /app/.venv and install dependencies from /app/pyproject.toml
ENV VIRTUAL_ENV=/app/.venv
ENV PATH="$VIRTUAL_ENV/bin:$PATH"
RUN $uv venv $VIRTUAL_ENV
RUN $uv sync --locked

EXPOSE 8000

# Start the FastAPI application using uvicorn
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]